services:
  - type: web
    name: digital-logbook
    env: python
    plan: free
    disk:
      sizeGb: 1
      mountPath: /data
    buildCommand: "mkdir -p /data && pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "bash start.sh"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: sist_project.settings
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: WEB_CONCURRENCY
        value: 2
      - key: USE_SQLITE
        value: "true"
      - key: SQLITE_DB_PATH
        value: "/data/db.sqlite3"
      - key: RENDER
        value: "true"
      - key: DEBUG
        value: "false"
