services:
  - type: web
    name: digital-logbook
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput"
    startCommand: "gunicorn sist_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: sist_project.settings
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: WEB_CONCURRENCY
        value: 2
      - key: SQLITE_DB_PATH
        value: /var/data/db.sqlite3
      - key: USE_SQLITE
        value: "true"