# Generated by Django 6.0.6 on 2026-08-07 11:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_systemsettings_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentperiod',
            name='field_supervisor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='field_supervisor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attachmentperiod',
            name='final_report',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models._sist_reports_upload_path),
        ),
        migrations.AlterField(
            model_name='attachmentperiod',
            name='week_12_grading_doc',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models._sist_reports_week12_upload_path),
        ),
        migrations.AlterField(
            model_name='attachmentperiod',
            name='week_12_returned_doc',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models._sist_reports_week12_returned_upload_path),
        ),
        migrations.AlterField(
            model_name='attachmentperiod',
            name='week_7_grading_doc',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models._sist_reports_week7_upload_path),
        ),
        migrations.AlterField(
            model_name='attachmentperiod',
            name='week_7_returned_doc',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models._sist_reports_week7_returned_upload_path),
        ),
    ]
