# Generated by Django 6.0.6 on 2026-08-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_attachmentperiod_recommendation_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentperiod',
            name='academic_year',
            field=models.CharField(default='2025/2026', max_length=20),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='current_academic_year',
            field=models.CharField(default='2025/2026', max_length=20),
        ),
    ]
