# Generated by Django 6.0.6 on 2026-09-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_attachmentperiod_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentperiod',
            name='week_12_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='week_7_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
