from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.urls import reverse
from django.views.decorators.http import require_GET
from django.db.models import Q
from .models import User, AttachmentPeriod, WeeklyLog
from .auth_utils import normalize_username
from .forms import SISTRegistrationForm, SISTLoginForm, LogEntryForm, SupervisorCommentForm, LecturerSignForm, FinalReportForm, FinalSupervisorGradingForm, FinalLecturerGradingForm


def landing_page(request):
    # This points directly to the login interface template generated by your setup script
    return render(request, 'core/login.html')
from django.contrib.auth import authenticate, login
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect

@csrf_protect
def login_view(request):
    if request.method == 'POST':
        registration_number = request.POST.get('username')
        password = request.POST.get('password')

        candidate_usernames = [registration_number]
        normalized_username = normalize_username(registration_number)
        if normalized_username and normalized_username not in candidate_usernames:
            candidate_usernames.append(normalized_username)

        user = None
        for candidate in candidate_usernames:
            user = authenticate(request, username=candidate, password=password)
            if user is not None:
                break

        if user is not None:
            login(request, user)
            return JsonResponse({'status': 'success', 'redirect_url': reverse('core:dashboard')})
        else:
            return JsonResponse({
                'status': 'error',
                'message': 'Invalid Registration Number or Password combination.'
            }, status=401)

    return render(request, 'core/login.html')
from django.http import JsonResponse
from django.shortcuts import render
# Remove 'login' and 'redirect' imports if you aren't using them elsewhere in this file

def register_view(request):
    if request.method == 'POST':
        form = SISTRegistrationForm(request.POST)
        if form.is_valid():
            # 1. Save the new account data safely into your database
            user = form.save()
            
            # 2. Return clean JSON instead of logging in or doing a Python redirect.
            # This triggers the frontend JavaScript to show your success message and point to login!
            return JsonResponse({'status': 'success'})
        else:
            # 3. If there are form errors (e.g., matching errors, password rules), return them
            errors = form.errors.get_json_data()
            compressed = []
            for field, entries in errors.items():
                for entry in entries:
                    compressed.append(f"{field}: {entry.get('message', 'Invalid input')}" )
            return JsonResponse({'status': 'error', 'message': 'Please correct the highlighted fields.', 'errors': compressed}, status=400)
            
    else:
        form = SISTRegistrationForm()
        
    return render(request, 'core/register.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('core:login')


def _normalize_company_name(value):
    return (value or '').strip().lower()


def _ensure_next_weekly_log(period):
    existing_week_numbers = set(
        WeeklyLog.objects.filter(profile=period).values_list('week_number', flat=True)
    )

    for week_number in range(1, period.total_weeks + 1):
        if week_number not in existing_week_numbers:
            return WeeklyLog.objects.create(profile=period, week_number=week_number)

    return None


def _assign_supervisor_if_matches(period, supervisor):
    if not supervisor or not period or period.supervisor_id == supervisor.id:
        return False

    student_company = _normalize_company_name(getattr(period.student, 'institution_or_company', ''))
    supervisor_company = _normalize_company_name(getattr(supervisor, 'institution_or_company', ''))

    if not student_company or not supervisor_company:
        return False

    if student_company == supervisor_company or student_company in supervisor_company or supervisor_company in student_company:
        period.supervisor = supervisor
        period.save(update_fields=['supervisor'])
        return True

    return False


def _ensure_period_assignments(period):
    changed = False

    if not period.supervisor_id:
        company_name = (period.student.institution_or_company or '').strip()
        supervisor = None

        if company_name:
            # Supervisors match by organisation only — no course filter
            supervisor = User.objects.filter(
                role='SUPERVISOR',
                institution_or_company__icontains=company_name
            ).order_by('id').first()

        if not supervisor:
            supervisor = User.objects.filter(role='SUPERVISOR').order_by('id').first()

        if supervisor:
            period.supervisor = supervisor
            changed = True

    if not period.lecturer_id:
        lecturer_qs = User.objects.filter(role='LECTURER')
        if period.student.course:
            lecturer_qs = lecturer_qs.filter(course=period.student.course)
        lecturer = lecturer_qs.order_by('id').first()
        if not lecturer:
            lecturer = User.objects.filter(role='LECTURER').order_by('id').first()
        if lecturer:
            period.lecturer = lecturer
            changed = True

    if changed:
        period.save()

    return period


@login_required
def dashboard_view(request):
    user = request.user
    if user.role == 'STUDENT':
        period, _ = AttachmentPeriod.objects.get_or_create(student=user, defaults={'start_date': '2026-01-01'})
        _ensure_period_assignments(period)

        logs = list(period.weekly_logs.order_by('week_number'))
        log_rows = []
        previous_approved = True
        for log in logs:
            activity_entered = any([
                bool(log.monday_activity),
                bool(log.tuesday_activity),
                bool(log.wednesday_activity),
                bool(log.thursday_activity),
                bool(log.friday_activity),
            ])
            can_edit = not log.supervisor_approved and (log.week_number == 1 or previous_approved)
            log_rows.append({'log': log, 'can_edit': can_edit, 'locked': not can_edit and not log.supervisor_approved, 'activity_entered': activity_entered})
            previous_approved = log.supervisor_approved

        latest_log = logs[-1] if logs else None
        can_add_log = True
        if latest_log and latest_log.supervisor_approved is False and any([
            bool(latest_log.monday_activity),
            bool(latest_log.tuesday_activity),
            bool(latest_log.wednesday_activity),
            bool(latest_log.thursday_activity),
            bool(latest_log.friday_activity),
        ]):
            can_add_log = False

        report_form = FinalReportForm(instance=period)
        if request.method == 'POST' and 'upload_report' in request.POST:
            report_form = FinalReportForm(request.POST, request.FILES, instance=period)
            if report_form.is_valid():
                report_form.save()
                return redirect('dashboard')

        return render(request, 'core/student_dashboard.html', {
            'period': period,
            'log_rows': log_rows,
            'can_add_log': can_add_log,
            'report_form': report_form,
        })
        
    elif user.role == 'SUPERVISOR':
        unassigned_periods = AttachmentPeriod.objects.filter(supervisor__isnull=True).select_related('student')
        for period in unassigned_periods:
            _assign_supervisor_if_matches(period, user)

        students_qs = AttachmentPeriod.objects.filter(supervisor=user)
        # Supervisors see all students in their organisation — no course filter

        students = list(
            students_qs.select_related('student', 'supervisor', 'lecturer')
            .prefetch_related('weekly_logs')
        )

        week_groups = []
        for week_number in range(1, 15):
            entries = []
            for period in students:
                log = period.weekly_logs.filter(week_number=week_number).first()
                entries.append({'period': period, 'log': log})
            week_groups.append({
                'week_number': week_number,
                'entries': entries,
                'has_pending': any(entry['log'] and not entry['log'].supervisor_approved for entry in entries),
            })

        pending_count = WeeklyLog.objects.filter(profile__supervisor=user, supervisor_approved=False).count()
        verified_count = WeeklyLog.objects.filter(profile__supervisor=user, supervisor_approved=True).count()
        return render(
            request,
            'core/supervisor_dashboard.html',
            {
                'students': students,
                'pending_count': pending_count,
                'verified_count': verified_count,
                'week_groups': week_groups,
                'week_range': range(1, 15),
            },
        )
        
    elif user.role == 'LECTURER':
        students = (
            AttachmentPeriod.objects.filter(lecturer=user)
            .select_related('student', 'supervisor', 'lecturer')
            .prefetch_related('weekly_logs')
        )

        selected_course = request.GET.get('course', '')
        if selected_course:
            if selected_course == '__unassigned__':
                students = students.filter(Q(student__course__isnull=True) | Q(student__course=''))
                log_filter_course = Q(profile__student__course__isnull=True) | Q(profile__student__course='')
            else:
                students = students.filter(student__course=selected_course)
                log_filter_course = Q(profile__student__course=selected_course)
        else:
            log_filter_course = Q()

        ready_for_lecturer_count = WeeklyLog.objects.filter(profile__lecturer=user, supervisor_approved=True, lecturer_approved=False).filter(log_filter_course).count()

        course_values = AttachmentPeriod.objects.filter(lecturer=user).values_list('student__course', flat=True).distinct()
        course_options = []
        seen = set()
        for course_value in course_values:
            if not course_value and '__unassigned__' not in seen:
                course_options.append(('__unassigned__', 'Unassigned / General Courses'))
                seen.add('__unassigned__')
            elif course_value and course_value not in seen:
                course_options.append((course_value, course_value))
                seen.add(course_value)

        return render(
            request,
            'core/lecturer_dashboard.html',
            {
                'students': students,
                'ready_for_lecturer_count': ready_for_lecturer_count,
                'course_options': course_options,
                'selected_course': selected_course,
            },
        )


@login_required
def create_log_view(request, period_id):
    # Allow a student to create/add a new weekly log for their attachment period.
    period = get_object_or_404(AttachmentPeriod, id=period_id)
    # Only the student who owns the period may create logs here
    if request.user != period.student or request.user.role != 'STUDENT':
        return HttpResponseForbidden()

    _ensure_period_assignments(period)

    latest_log = period.weekly_logs.order_by('-week_number').first()
    if latest_log and (
        latest_log.monday_activity or latest_log.tuesday_activity or latest_log.wednesday_activity or
        latest_log.thursday_activity or latest_log.friday_activity
    ) and not latest_log.supervisor_approved:
        return HttpResponseForbidden("Please wait for your supervisor to approve the current weekly log before creating the next one.")

    # Find the next week that has no activity entered yet.
    next_week = period.weekly_logs.filter(
        monday_activity__isnull=True,
        tuesday_activity__isnull=True,
        wednesday_activity__isnull=True,
        thursday_activity__isnull=True,
        friday_activity__isnull=True,
    ).order_by('week_number').first()

    if next_week:
        return redirect('core:edit_log', log_id=next_week.id)

    # Create only the next missing weekly log entry when none are still empty.
    created_log = _ensure_next_weekly_log(period)
    if created_log:
        return redirect('core:edit_log', log_id=created_log.id)
    # If all weeks already have entries, go back to dashboard
    return redirect('core:dashboard')

@login_required
def edit_week_log(request, log_id):
    log = get_object_or_404(WeeklyLog, id=log_id, profile__student=request.user)
    if log.supervisor_approved:
        return HttpResponseForbidden("This week's entry has been verified and locked.")
    if request.method == 'POST':
        form = LogEntryForm(request.POST, instance=log)
        if form.is_valid():
            form.save()
            return redirect('core:dashboard')
    else:
        form = LogEntryForm(instance=log)
    return render(request, 'core/edit_log.html', {'form': form, 'log': log})

@login_required
def supervisor_review_log(request, log_id):
    if request.user.role != 'SUPERVISOR': return HttpResponseForbidden()
    log = get_object_or_404(WeeklyLog, id=log_id, profile__supervisor=request.user)
    if request.method == 'POST':
        form = SupervisorCommentForm(request.POST, instance=log)
        if form.is_valid():
            form.save()
            return redirect('core:dashboard')
    else:
        form = SupervisorCommentForm(instance=log)
    return render(request, 'core/review_log.html', {'form': form, 'log': log, 'role': 'Supervisor'})

@login_required
def lecturer_sign_log(request, log_id):
    if request.user.role != 'LECTURER': return HttpResponseForbidden()
    log = get_object_or_404(WeeklyLog, id=log_id, profile__lecturer=request.user)
    if not log.supervisor_approved:
        return HttpResponseForbidden("You can only sign logs that have been verified by the Industry Supervisor.")
    if request.method == 'POST':
        form = LecturerSignForm(request.POST, instance=log)
        if form.is_valid():
            form.save()
            return redirect('core:dashboard')
    else:
        form = LecturerSignForm(instance=log)
    return render(request, 'core/review_log.html', {'form': form, 'log': log, 'role': 'Lecturer'})

@login_required
def final_grading_view(request, period_id):
    period = get_object_or_404(AttachmentPeriod, id=period_id)
    if request.user.role == 'SUPERVISOR' and period.supervisor == request.user:
        form = FinalSupervisorGradingForm(instance=period)
        if request.method == 'POST':
            form = FinalSupervisorGradingForm(request.POST, instance=period)
            if form.is_valid(): form.save(); return redirect('core:dashboard')
        return render(request, 'core/final_grading.html', {'form': form, 'period': period, 'role': 'Supervisor'})
        
    elif request.user.role == 'LECTURER' and period.lecturer == request.user:
        if not period.supervisor_signed:
            return HttpResponseForbidden("Waiting for Industry Supervisor's final assessment and signature.")
        form = FinalLecturerGradingForm(instance=period)
        if request.method == 'POST':
            form = FinalLecturerGradingForm(request.POST, instance=period)
            if form.is_valid(): form.save(); return redirect('core:dashboard')
        return render(request, 'core/final_grading.html', {'form': form, 'period': period, 'role': 'Lecturer'})
    return HttpResponseForbidden()


@require_GET
def debug_login_supervisor(request):
    super_username = 'SUP123'
    super_password = 'Demo1234!'

    supervisor, created = User.objects.get_or_create(
        username=super_username,
        defaults={
            'first_name': 'Temp',
            'last_name': 'Supervisor',
            'role': 'SUPERVISOR',
            'email': 'temp.supervisor@example.com',
            'institution_or_company': 'Kisii Region Depot',
        }
    )
    if created or not supervisor.has_usable_password():
        supervisor.set_password(super_password)
        supervisor.save()

    student, created_student = User.objects.get_or_create(
        username='STU123',
        defaults={
            'first_name': 'Demo',
            'last_name': 'Student',
            'role': 'STUDENT',
            'email': 'demo.student@example.com',
            'institution_or_company': 'Kisii University (SIST)',
        }
    )
    if created_student or not student.has_usable_password():
        student.set_password('Student1234!')
        student.save()

    period, _ = AttachmentPeriod.objects.get_or_create(
        student=student,
        defaults={
            'supervisor': supervisor,
            'start_date': '2026-01-01',
        }
    )
    if period.supervisor_id != supervisor.id:
        period.supervisor = supervisor
        period.save()

    for week_num in range(1, 5):
        WeeklyLog.objects.get_or_create(
            profile=period,
            week_number=week_num,
            defaults={
                'monday_activity': 'Site orientation and health briefing.',
                'tuesday_activity': 'Reviewed safety procedures and daily log entries.',
                'wednesday_activity': 'Assisted with inventory and stock reconciliation.',
                'thursday_activity': 'Prepared weekly progress summary and supervisor notes.',
                'friday_activity': 'Finalized attachments report and supervisor review.',
                'supervisor_approved': False,
            }
        )

    login(request, supervisor)
    return redirect(reverse('core:dashboard'))

# Inside your views.py dashboard controller
# Note: student dashboard is handled by `dashboard_view` above which renders
# the appropriate template depending on `request.user.role`.