import re
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden
from django.urls import reverse
from django.views.decorators.http import require_GET
from django.db import IntegrityError
from django.db.models import Q
from .models import User, AttachmentPeriod, WeeklyLog
from .auth_utils import normalize_username
from .forms import SISTRegistrationForm, SISTLoginForm, LogEntryForm, SupervisorCommentForm, LecturerSignForm, FinalReportForm, FinalSupervisorGradingForm, FinalLecturerGradingForm
from django.views.decorators.http import require_POST
from django.http import JsonResponse


def info_page_view(request, page_name):
    # Mapping friendly URLs to titles
    titles = {
        'guidelines': 'Attachment Guidelines',
        'manuals': 'Supervisor Manuals',
        'support': 'Logbook Support Help',
        'report': 'Report System Issues'
    }
    title = titles.get(page_name, 'Information Page')
    
    if page_name in ['manuals', 'guidelines']:
        return render(request, 'core/logbook_manual.html', {'title': title})
        
    return render(request, 'core/info_page.html', {'title': title, 'page_name': page_name})


def landing_page(request):
    # This points directly to the login interface template generated by your setup script
    return render(request, 'core/login.html')
from django.views.decorators.csrf import csrf_protect

@csrf_protect
def login_view(request):
    if request.method == 'POST':
        registration_number = request.POST.get('username')
        password = request.POST.get('password')
        selected_role = request.POST.get('role', 'STUDENT')

        candidate_usernames = [registration_number]
        normalized_username = normalize_username(registration_number)
        if normalized_username and normalized_username not in candidate_usernames:
            candidate_usernames.append(normalized_username)

        user = None
        for candidate in candidate_usernames:
            user = authenticate(request, username=candidate, password=password)
            if user is not None:
                break

        if user is not None:
            if selected_role == 'ADMIN':
                if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                    return JsonResponse({'status': 'error', 'message': 'Please use the dedicated admin portal to access administrator features.'}, status=403)
                return render(request, 'core/login.html', {'error': 'Please use the dedicated admin portal to access administrator features.'})

            # Validate that the user's actual role matches the selected role
            if user.role != selected_role:
                msg = f'This account is registered as a {user.get_role_display()}. Please select the correct role or use the correct account.'
                if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                    return JsonResponse({'status': 'error', 'message': msg}, status=401)
                return render(request, 'core/login.html', {'error': msg})
            
            login(request, user)
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'status': 'success', 'redirect_url': reverse('core:dashboard')})
            return redirect('core:dashboard')
        else:
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'status': 'error', 'message': 'Invalid Registration Number or Password combination.'}, status=401)
            return render(request, 'core/login.html', {'error': 'Invalid Registration Number or Password combination.'})

    return render(request, 'core/login.html')

def register_view(request):
    if request.method == 'POST':
        form = SISTRegistrationForm(request.POST)
        if form.is_valid():
            try:
                # 1. Save the new account data safely into your database
                user = form.save()
            except IntegrityError as exc:
                if 'unique_lower_email' in str(exc):
                    form.add_error('email', 'An account with this email already exists.')
                else:
                    form.add_error(None, 'A database error occurred while creating your account. Please try again.')
            else:
                # 2. Return clean JSON instead of logging in or doing a Python redirect.
                # This triggers the frontend JavaScript to show your success message and point to login!
                if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                    return JsonResponse({'status': 'success'})
                return redirect(f"{reverse('core:login')}?registered=true")
        if form.errors:
            # 3. If there are form errors (e.g., matching errors, password rules), return them
            errors = form.errors.get_json_data()
            compressed = []
            first_message = None
            for field, entries in errors.items():
                for entry in entries:
                    raw_msg = entry.get('message', 'Invalid input')
                    # Make username duplicate errors more user-friendly
                    if field == 'username' and 'already exists' in raw_msg.lower():
                        friendly = 'A user with that Registration Number / Staff ID already exists in the database.'
                    elif field == '__all__':
                        friendly = raw_msg
                    else:
                        friendly = f"{field.replace('_', ' ').title()}: {raw_msg}"
                    compressed.append(friendly)
                    if not first_message:
                        first_message = friendly
            summary = first_message or 'Please correct the highlighted fields.'
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                return JsonResponse({'status': 'error', 'message': summary, 'errors': compressed}, status=400)
            return render(request, 'core/register.html', {
                'form': form,
                'errors': compressed,
                'error_summary': summary,
            })
            
    else:
        form = SISTRegistrationForm()
        
    return render(request, 'core/register.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('core:login')


def _normalize_company_name(value):
    return re.sub(r'[^a-z0-9]', '', (value or '').strip().lower())


def _companies_match(student_company, supervisor_company):
    normalized_student = _normalize_company_name(student_company)
    normalized_supervisor = _normalize_company_name(supervisor_company)

    if not normalized_student or not normalized_supervisor:
        return False

    if normalized_student == normalized_supervisor:
        return True

    return normalized_student in normalized_supervisor or normalized_supervisor in normalized_student


def _find_matching_supervisor(student_company):
    if not student_company:
        return None

    for supervisor in User.objects.filter(role='SUPERVISOR').order_by('id'):
        if _companies_match(student_company, getattr(supervisor, 'institution_or_company', '')):
            return supervisor

    return None


def _ensure_next_weekly_log(period):
    existing_week_numbers = set(
        WeeklyLog.objects.filter(profile=period).values_list('week_number', flat=True)
    )

    for week_number in range(1, period.total_weeks + 1):
        if week_number not in existing_week_numbers:
            return WeeklyLog.objects.create(profile=period, week_number=week_number)

    return None


def _assign_supervisor_if_matches(period, supervisor):
    if not supervisor or not period or period.supervisor_id == supervisor.id:
        return False

    student_company = getattr(period.student, 'institution_or_company', '')
    supervisor_company = getattr(supervisor, 'institution_or_company', '')

    if _companies_match(student_company, supervisor_company):
        period.supervisor = supervisor
        period.save(update_fields=['supervisor'])
        return True

    return False


def _ensure_period_assignments(period):
    changed = False

    if not period.supervisor_id:
        company_name = (period.student.institution_or_company or '').strip()
        supervisor = _find_matching_supervisor(company_name)
        if supervisor:
            period.supervisor = supervisor
            changed = True

    if not period.lecturer_id and period.student.course:
        lecturer = User.objects.filter(role='LECTURER', course=period.student.course).order_by('id').first()
        if lecturer:
            period.lecturer = lecturer
            changed = True

    if changed:
        period.save()

    return period


@login_required
def dashboard_view(request):
    user = request.user
    if user.role == 'ADMIN':
        return redirect('core:admin_dashboard')

    if user.role == 'STUDENT':
        period, _ = AttachmentPeriod.objects.get_or_create(student=user, defaults={'start_date': '2026-01-01'})
        _ensure_period_assignments(period)

        logs = list(period.weekly_logs.order_by('week_number'))
        log_rows = []
        previous_approved = True
        for log in logs:
            activity_entered = any([
                bool(log.monday_activity),
                bool(log.tuesday_activity),
                bool(log.wednesday_activity),
                bool(log.thursday_activity),
                bool(log.friday_activity),
            ])
            can_edit = not log.supervisor_approved and (log.week_number == 1 or previous_approved)
            log_rows.append({'log': log, 'can_edit': can_edit, 'locked': not can_edit and not log.supervisor_approved, 'activity_entered': activity_entered})
            previous_approved = log.supervisor_approved

        latest_log = logs[-1] if logs else None
        can_add_log = True
        if latest_log and latest_log.supervisor_approved is False and any([
            bool(latest_log.monday_activity),
            bool(latest_log.tuesday_activity),
            bool(latest_log.wednesday_activity),
            bool(latest_log.thursday_activity),
            bool(latest_log.friday_activity),
        ]):
            can_add_log = False

        report_form = FinalReportForm(instance=period)
        if request.method == 'POST' and 'upload_report' in request.POST:
            report_form = FinalReportForm(request.POST, request.FILES, instance=period)
            if report_form.is_valid():
                period = report_form.save()
                period.report_status = 'PENDING_REVIEW'
                period.report_review_comment = ''
                period.save(update_fields=['report_status', 'report_review_comment'])
                return redirect('core:dashboard')

        return render(request, 'core/student_dashboard.html', {
            'period': period,
            'log_rows': log_rows,
            'can_add_log': can_add_log,
            'report_form': report_form,
            'can_download_full_log': len(log_rows) >= 12,
        })
        
    elif user.role == 'SUPERVISOR':
        unassigned_periods = AttachmentPeriod.objects.filter(supervisor__isnull=True).select_related('student')
        for period in unassigned_periods:
            _assign_supervisor_if_matches(period, user)

        students_qs = AttachmentPeriod.objects.filter(supervisor=user)
        students = [
            period for period in students_qs.select_related('student', 'supervisor', 'lecturer').prefetch_related('weekly_logs')
            if _companies_match(getattr(period.student, 'institution_or_company', ''), getattr(user, 'institution_or_company', ''))
        ]

        week_groups = []
        for week_number in range(1, 15):
            entries = []
            for period in students:
                log = period.weekly_logs.filter(week_number=week_number).first()
                entries.append({'period': period, 'log': log})
            week_groups.append({
                'week_number': week_number,
                'entries': entries,
                'has_pending': any(entry['log'] and not entry['log'].supervisor_approved for entry in entries),
            })

        pending_count = WeeklyLog.objects.filter(profile__supervisor=user, supervisor_approved=False).count()
        verified_count = WeeklyLog.objects.filter(profile__supervisor=user, supervisor_approved=True).count()
        return render(
            request,
            'core/supervisor_dashboard.html',
            {
                'students': students,
                'pending_count': pending_count,
                'verified_count': verified_count,
                'week_groups': week_groups,
                'week_range': range(1, 15),
            },
        )
        
    elif user.role == 'LECTURER':
        students_qs = AttachmentPeriod.objects.filter(lecturer=user)
        lecturer_course = user.course
        if lecturer_course:
            students_qs = students_qs.filter(student__course=lecturer_course)

        selected_course = request.GET.get('course', '')
        if selected_course:
            if selected_course == '__unassigned__':
                students_qs = students_qs.filter(Q(student__course__isnull=True) | Q(student__course=''))
                log_filter_course = Q(profile__student__course__isnull=True) | Q(profile__student__course='')
            else:
                students_qs = students_qs.filter(student__course=selected_course)
                log_filter_course = Q(profile__student__course=selected_course)
        else:
            log_filter_course = Q()

        students = list(
            students_qs.select_related('student', 'supervisor', 'lecturer')
            .prefetch_related('weekly_logs')
        )

        ready_for_lecturer_count = WeeklyLog.objects.filter(profile__in=students_qs, supervisor_approved=True, lecturer_approved=False).filter(log_filter_course).count()

        course_values = AttachmentPeriod.objects.filter(lecturer=user).values_list('student__course', flat=True).distinct()
        course_options = []
        seen = set()
        for course_value in course_values:
            if not course_value and '__unassigned__' not in seen:
                course_options.append(('__unassigned__', 'Unassigned / General Courses'))
                seen.add('__unassigned__')
            elif course_value and course_value not in seen:
                course_options.append((course_value, course_value))
                seen.add(course_value)

        pending_reports = AttachmentPeriod.objects.filter(
            lecturer=user,
            report_status__in=['PENDING_REVIEW', 'RETURNED'],
        ).select_related('student').order_by('-id')

        return render(
            request,
            'core/lecturer_dashboard.html',
            {
                'students': students,
                'ready_for_lecturer_count': ready_for_lecturer_count,
                'course_options': course_options,
                'selected_course': selected_course,
                'pending_reports': pending_reports,
            },
        )


@login_required
@require_GET
def download_all_logs_view(request, period_id):
    period = get_object_or_404(AttachmentPeriod, id=period_id, student=request.user)
    logs = list(period.weekly_logs.order_by('week_number'))
    if len(logs) < 12:
        return HttpResponseForbidden("Full log download is available after 12 weeks of records.")

    return render(request, 'core/download_all_logs.html', {
        'period': period,
        'logs': logs,
    })


def admin_login_view(request):
    if request.user.is_authenticated:
        if request.user.role == 'ADMIN':
            return redirect('core:admin_dashboard')
        logout(request)

    if request.method == 'POST':
        username = request.POST.get('username', '').strip()
        password = request.POST.get('password', '')
        user = authenticate(request, username=username, password=password)
        if user is not None and user.role == 'ADMIN':
            login(request, user)
            return redirect('core:admin_dashboard')

        return render(request, 'core/admin_login.html', {
            'error': 'Only system administrators can access this portal.'
        })

    return render(request, 'core/admin_login.html')


@login_required
def admin_dashboard_view(request):
    if request.user.role != 'ADMIN':
        return HttpResponseForbidden("Only the system administrator can access this control center.")

    selected_role = request.GET.get('role', '')
    role_choices = dict(User.ROLE_CHOICES)
    initial_data = {'role': selected_role} if selected_role in role_choices else {}
    form = SISTRegistrationForm(initial=initial_data)
    if request.method == 'POST':
        form = SISTRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:admin_dashboard')

    stats = {
        'total_users': User.objects.count(),
        'students': User.objects.filter(role='STUDENT').count(),
        'supervisors': User.objects.filter(role='SUPERVISOR').count(),
        'lecturers': User.objects.filter(role='LECTURER').count(),
        'admins': User.objects.filter(role='ADMIN').count(),
        'active_periods': AttachmentPeriod.objects.count(),
        'pending_reviews': WeeklyLog.objects.filter(supervisor_approved=False).count(),
    }
    role_groups = {
        'students': User.objects.filter(role='STUDENT').order_by('-date_joined'),
        'supervisors': User.objects.filter(role='SUPERVISOR').order_by('-date_joined'),
        'lecturers': User.objects.filter(role='LECTURER').order_by('-date_joined'),
        'admins': User.objects.filter(role='ADMIN').order_by('-date_joined'),
    }
    notice = None
    if selected_role:
        notice = f"Create a new {role_choices.get(selected_role, selected_role).lower()} account from the form below."

    return render(request, 'core/admin_dashboard.html', {
        'form': form,
        'stats': stats,
        'role_groups': role_groups,
        'selected_role': selected_role,
        'notice': notice,
    })


@login_required
def admin_create_user_view(request):
    if request.user.role != 'ADMIN':
        return HttpResponseForbidden("Only the system administrator can create users.")

    if request.method != 'POST':
        return redirect('core:admin_dashboard')

    form = SISTRegistrationForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('core:admin_dashboard')

    selected_role = request.POST.get('role', '')
    role_choices = dict(User.ROLE_CHOICES)
    notice = f"Please correct the highlighted fields for the {role_choices.get(selected_role, selected_role).lower()} account."
    return render(request, 'core/admin_dashboard.html', {'form': form, 'stats': {
        'total_users': User.objects.count(),
        'students': User.objects.filter(role='STUDENT').count(),
        'supervisors': User.objects.filter(role='SUPERVISOR').count(),
        'lecturers': User.objects.filter(role='LECTURER').count(),
        'admins': User.objects.filter(role='ADMIN').count(),
        'active_periods': AttachmentPeriod.objects.count(),
        'pending_reviews': WeeklyLog.objects.filter(supervisor_approved=False).count(),
    }, 'users': User.objects.order_by('-date_joined')[:12], 'selected_role': selected_role, 'notice': notice})


@login_required
@require_POST
def admin_manage_user_view(request, user_id):
    if request.user.role != 'ADMIN':
        return HttpResponseForbidden("Only the system administrator can manage user accounts.")

    target_user = get_object_or_404(User, id=user_id)
    action = request.POST.get('action', '').strip()

    if action == 'delete':
        if target_user == request.user:
            return redirect('core:admin_dashboard')
        target_user.delete()
        return redirect('core:admin_dashboard')

    if action == 'reset_password':
        new_password = request.POST.get('new_password', '').strip()
        if new_password:
            target_user.set_password(new_password)
            target_user.save(update_fields=['password'])
        return redirect('core:admin_dashboard')

    if action == 'edit':
        full_name = request.POST.get('full_name', '').strip()
        if full_name:
            parts = full_name.split()
            target_user.first_name = parts[0]
            target_user.last_name = ' '.join(parts[1:]) if len(parts) > 1 else ''

        email = request.POST.get('email', '').strip().lower()
        if email:
            target_user.email = email

        role = request.POST.get('role', target_user.role).strip()
        if role in dict(User.ROLE_CHOICES):
            target_user.role = role

        new_password = request.POST.get('new_password', '').strip()
        if new_password:
            target_user.set_password(new_password)

        target_user.phone_number = request.POST.get('phone_number', '').strip() or None
        target_user.institution_or_company = request.POST.get('institution_or_company', '').strip() or None
        target_user.course = request.POST.get('course', '').strip() or None
        target_user.save()

    return redirect('core:admin_dashboard')

@login_required
def create_log_view(request, period_id):
    # Allow a student to create/add a new weekly log for their attachment period.
    period = get_object_or_404(AttachmentPeriod, id=period_id)
    # Only the student who owns the period may create logs here
    if request.user != period.student or request.user.role != 'STUDENT':
        return HttpResponseForbidden()

    _ensure_period_assignments(period)

    latest_log = period.weekly_logs.order_by('-week_number').first()
    if latest_log and (
        latest_log.monday_activity or latest_log.tuesday_activity or latest_log.wednesday_activity or
        latest_log.thursday_activity or latest_log.friday_activity
    ) and not latest_log.supervisor_approved:
        return HttpResponseForbidden("Please wait for your supervisor to approve the current weekly log before creating the next one.")

    # Find the next week that has no activity entered yet.
    next_week = period.weekly_logs.filter(
        monday_activity__isnull=True,
        tuesday_activity__isnull=True,
        wednesday_activity__isnull=True,
        thursday_activity__isnull=True,
        friday_activity__isnull=True,
    ).order_by('week_number').first()

    if next_week:
        return redirect('core:edit_log', log_id=next_week.id)

    # Create only the next missing weekly log entry when none are still empty.
    created_log = _ensure_next_weekly_log(period)
    if created_log:
        return redirect('core:edit_log', log_id=created_log.id)
    # If all weeks already have entries, go back to dashboard
    return redirect('core:dashboard')

@login_required
def edit_week_log(request, log_id):
    log = get_object_or_404(WeeklyLog, id=log_id, profile__student=request.user)
    if log.supervisor_approved:
        return HttpResponseForbidden("This week's entry has been verified and locked.")
    if request.method == 'POST':
        form = LogEntryForm(request.POST, instance=log)
        if form.is_valid():
            form.save()
            return redirect('core:dashboard')
    else:
        form = LogEntryForm(instance=log)
    return render(request, 'core/edit_log.html', {'form': form, 'log': log})

@login_required
def supervisor_review_log(request, log_id):
    if request.user.role != 'SUPERVISOR': return HttpResponseForbidden()
    log = get_object_or_404(WeeklyLog, id=log_id, profile__supervisor=request.user)
    if request.method == 'POST':
        form = SupervisorCommentForm(request.POST, instance=log)
        if form.is_valid():
            form.save()
            return redirect('core:dashboard')
    else:
        form = SupervisorCommentForm(instance=log)
    return render(request, 'core/review_log.html', {'form': form, 'log': log, 'role': 'Supervisor'})

# PASTE IT RIGHT HERE AT THE SAME LEVEL
@login_required
@require_POST
def update_profile_meta(request):
    user = request.user
    
    if 'profile_photo' in request.FILES:
        user.profile_photo = request.FILES['profile_photo']
        user.save()
        return JsonResponse({'status': 'success', 'url': user.profile_photo.url})
        
    elif 'avatar_color' in request.POST:
        user.avatar_color = request.POST.get('avatar_color')
        user.save()
        return JsonResponse({'status': 'success'})
        
    return JsonResponse({'status': 'failed', 'message': 'No valid data provided.'}, status=400)
@login_required
def lecturer_sign_log(request, log_id):
    if request.user.role != 'LECTURER': return HttpResponseForbidden()
    log = get_object_or_404(WeeklyLog, id=log_id, profile__lecturer=request.user)
    if not log.supervisor_approved:
        return HttpResponseForbidden("You can only sign logs that have been verified by the Industry Supervisor.")
    if request.method == 'POST':
        form = LecturerSignForm(request.POST, instance=log)
        if form.is_valid():
            form.save()
            return redirect('core:dashboard')
    else:
        form = LecturerSignForm(instance=log)
    return render(request, 'core/review_log.html', {'form': form, 'log': log, 'role': 'Lecturer'})

@login_required
def review_final_report(request, period_id):
    period = get_object_or_404(AttachmentPeriod, id=period_id)
    if request.user.role != 'LECTURER' or period.lecturer_id != request.user.id:
        return HttpResponseForbidden("Only the assigned lecturer can review final reports.")

    if request.method == 'POST':
        action = request.POST.get('report_action', '').strip()
        comment = request.POST.get('report_review_comment', '').strip()
        if action == 'approve':
            period.report_status = 'APPROVED'
        elif action == 'return':
            period.report_status = 'RETURNED'
        else:
            period.report_status = 'PENDING_REVIEW'

        period.report_review_comment = comment
        period.save(update_fields=['report_status', 'report_review_comment'])
        return redirect('core:dashboard')

    return render(request, 'core/review_final_report.html', {'period': period})

@login_required
def final_grading_view(request, period_id):
    period = get_object_or_404(AttachmentPeriod, id=period_id)
    if request.user.role == 'SUPERVISOR' and period.supervisor == request.user:
        form = FinalSupervisorGradingForm(instance=period)
        if request.method == 'POST':
            form = FinalSupervisorGradingForm(request.POST, instance=period)
            if form.is_valid(): form.save(); return redirect('core:dashboard')
        return render(request, 'core/final_grading.html', {'form': form, 'period': period, 'role': 'Supervisor'})
        
    elif request.user.role == 'LECTURER' and period.lecturer == request.user:
        if not period.supervisor_signed:
            return HttpResponseForbidden("Waiting for Industry Supervisor's final assessment and signature.")
        form = FinalLecturerGradingForm(instance=period)
        if request.method == 'POST':
            form = FinalLecturerGradingForm(request.POST, instance=period)
            if form.is_valid(): form.save(); return redirect('core:dashboard')
        return render(request, 'core/final_grading.html', {'form': form, 'period': period, 'role': 'Lecturer'})
    return HttpResponseForbidden()

@login_required
@require_POST
def submit_assessment_form(request, period_id):
    period = get_object_or_404(AttachmentPeriod, id=period_id)
    user = request.user
    
    if user.role == 'STUDENT' and period.student == user:
        if 'student_additional_info' in request.POST:
            period.student_additional_info = request.POST.get('student_additional_info')
            
    elif user.role == 'LECTURER' and period.lecturer == user:
        if 'first_visit_comment' in request.POST:
            period.first_visit_comment = request.POST.get('first_visit_comment')
            period.first_visit_date = request.POST.get('first_visit_date') or None
        if 'second_visit_comment' in request.POST:
            period.second_visit_comment = request.POST.get('second_visit_comment')
            period.second_visit_date = request.POST.get('second_visit_date') or None
        if 'week_7_grading_doc' in request.FILES:
            period.week_7_grading_doc = request.FILES['week_7_grading_doc']
        if 'week_12_grading_doc' in request.FILES:
            period.week_12_grading_doc = request.FILES['week_12_grading_doc']
            
    elif user.role == 'SUPERVISOR' and period.supervisor == user:
        if 'industry_supervisor_final_comment' in request.POST:
            period.industry_supervisor_final_comment = request.POST.get('industry_supervisor_final_comment')
        if 'week_7_returned_doc' in request.FILES:
            period.week_7_returned_doc = request.FILES['week_7_returned_doc']
        if 'week_7_supervisor_marks' in request.POST and request.POST.get('week_7_supervisor_marks'):
            period.week_7_supervisor_marks = request.POST.get('week_7_supervisor_marks')
        if 'week_12_returned_doc' in request.FILES:
            period.week_12_returned_doc = request.FILES['week_12_returned_doc']
        if 'week_12_supervisor_marks' in request.POST and request.POST.get('week_12_supervisor_marks'):
            period.week_12_supervisor_marks = request.POST.get('week_12_supervisor_marks')
            
    period.save()
    return redirect('core:dashboard')


@require_GET
def debug_login_supervisor(request):
    super_username = 'SUP123'
    super_password = 'Demo1234!'

    supervisor, created = User.objects.get_or_create(
        username=super_username,
        defaults={
            'first_name': 'Temp',
            'last_name': 'Supervisor',
            'role': 'SUPERVISOR',
            'email': 'temp.supervisor@example.com',
            'institution_or_company': 'Kisii Region Depot',
        }
    )
    if created or not supervisor.has_usable_password():
        supervisor.set_password(super_password)
        supervisor.save()

    student, created_student = User.objects.get_or_create(
        username='STU123',
        defaults={
            'first_name': 'Demo',
            'last_name': 'Student',
            'role': 'STUDENT',
            'email': 'demo.student@example.com',
            'institution_or_company': 'Kisii University (SIST)',
        }
    )
    if created_student or not student.has_usable_password():
        student.set_password('Student1234!')
        student.save()

    period, _ = AttachmentPeriod.objects.get_or_create(
        student=student,
        defaults={
            'supervisor': supervisor,
            'start_date': '2026-01-01',
        }
    )
    if period.supervisor_id != supervisor.id:
        period.supervisor = supervisor
        period.save()

    for week_num in range(1, 5):
        WeeklyLog.objects.get_or_create(
            profile=period,
            week_number=week_num,
            defaults={
                'monday_activity': 'Site orientation and health briefing.',
                'tuesday_activity': 'Reviewed safety procedures and daily log entries.',
                'wednesday_activity': 'Assisted with inventory and stock reconciliation.',
                'thursday_activity': 'Prepared weekly progress summary and supervisor notes.',
                'friday_activity': 'Finalized attachments report and supervisor review.',
                'supervisor_approved': False,
            }
        )

    login(request, supervisor)
    return redirect(reverse('core:dashboard'))

# Inside your views.py dashboard controller
# Note: student dashboard is handled by `dashboard_view` above which renders
# the appropriate template depending on `request.user.role`.

