# Generated by Django 6.0.6 on 2026-07-06 04:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('SUPERVISOR', 'Industry Supervisor'), ('LECTURER', 'University Lecturer')], default='STUDENT', max_length=15)),
                ('institution_or_company', models.CharField(blank=True, default='Kisii University (SIST)', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('course', models.CharField(blank=True, max_length=120, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('total_weeks', models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(16)])),
                ('final_report', models.FileField(blank=True, null=True, upload_to='sist_reports/')),
                ('supervisor_marks', models.FloatField(blank=True, null=True)),
                ('supervisor_comment', models.TextField(blank=True, null=True)),
                ('supervisor_signed', models.BooleanField(default=False)),
                ('lecturer_grade', models.CharField(blank=True, max_length=2, null=True)),
                ('lecturer_marks', models.FloatField(blank=True, null=True)),
                ('lecturer_comment', models.TextField(blank=True, null=True)),
                ('lecturer_signed', models.BooleanField(default=False)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_profile', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('monday_activity', models.TextField(blank=True, null=True)),
                ('tuesday_activity', models.TextField(blank=True, null=True)),
                ('wednesday_activity', models.TextField(blank=True, null=True)),
                ('thursday_activity', models.TextField(blank=True, null=True)),
                ('friday_activity', models.TextField(blank=True, null=True)),
                ('supervisor_approved', models.BooleanField(default=False)),
                ('supervisor_comment', models.TextField(blank=True, null=True)),
                ('lecturer_approved', models.BooleanField(default=False)),
                ('lecturer_comment', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='core.attachmentperiod')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('profile', 'week_number')},
            },
        ),
    ]
