# Generated by Django 6.0.6 on 2026-07-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_avatar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentperiod',
            name='first_visit_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='first_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='industry_supervisor_final_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='second_visit_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='second_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='student_additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='week_12_grading_doc',
            field=models.FileField(blank=True, null=True, upload_to='sist_reports/week12/'),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='week_12_returned_doc',
            field=models.FileField(blank=True, null=True, upload_to='sist_reports/week12_returned/'),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='week_12_supervisor_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='week_7_grading_doc',
            field=models.FileField(blank=True, null=True, upload_to='sist_reports/week7/'),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='week_7_returned_doc',
            field=models.FileField(blank=True, null=True, upload_to='sist_reports/week7_returned/'),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='week_7_supervisor_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('SUPERVISOR', 'Industry Supervisor'), ('LECTURER', 'University Lecturer'), ('ADMIN', 'System Administrator')], default='STUDENT', max_length=15),
        ),
    ]
