# Generated by Django 6.0.6 on 2026-07-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_options_user_unique_lower_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentperiod',
            name='report_review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachmentperiod',
            name='report_status',
            field=models.CharField(default='NOT_SUBMITTED', max_length=24),
        ),
    ]
