# Generated by Django 6.0.6 on 2026-07-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attachmentperiod_report_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
