# Generated by Django 6.0.6 on 2026-07-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_enabled', models.BooleanField(default=True)),
                ('registration_closed_message', models.CharField(default='Registration is temporarily closed by the system administrator.', max_length=255)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('SUPERVISOR', 'Industry Supervisor'), ('LECTURER', 'University Lecturer'), ('ADMIN', 'System Administrator'), ('ATTACHMENT_ADMIN', 'Attachment Administrator')], default='STUDENT', max_length=20),
        ),
    ]
