# Generated by Django 6.0.6 on 2026-08-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_lecturerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('SIST', 'School of Information Sciences & Technology'), ('SASS', 'School of Arts and Social Sciences'), ('SOBE', 'School of Business and Economics'), ('SEDHURED', 'School of Education and Human Resource Development'), ('SHS', 'School of Health Sciences'), ('SLAW', 'School of Law'), ('SPAS', 'School of Pure and Applied Sciences'), ('SANRM', 'School of Agriculture and Natural Resources Management')], max_length=20, null=True),
        ),
    ]
