# Generated by Django 6.0.6 on 2026-08-20 22:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentperiod',
            name='recommendation_letter',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models._sist_reports_upload_path),
        ),
    ]
