# Generated by Django 6.0.6 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_attachmentperiod_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='audit_retention',
            field=models.CharField(default='90 days', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_new_account_role',
            field=models.CharField(default='STUDENT', max_length=30),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='logbook_lock_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notification_frequency',
            field=models.CharField(default='WEEKLY', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='placement_approval',
            field=models.CharField(default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_password_reset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='submission_deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='term_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='term_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
