# Generated by Django 6.0.6 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_systemsettings_schedule_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='landing_last_year_completed',
            field=models.IntegerField(default=456),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='landing_total_last_5_years',
            field=models.IntegerField(default=1458),
        ),
    ]
