# Generated by Django 6.0.6 on 2026-09-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='landing_manual_year_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
