# Generated by Django 6.0.6 on 2026-09-10 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_recalculate_student_final_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_role', models.CharField(choices=[('ALL', 'All (Students, Supervisors & Lecturers)'), ('STUDENT', 'Students Only'), ('SUPERVISOR', 'Industry Supervisors Only'), ('LECTURER', 'University Lecturers Only')], default='ALL', max_length=20)),
                ('priority', models.CharField(choices=[('INFO', 'Informational (Blue)'), ('WARNING', 'Important Notice (Yellow/Orange)'), ('URGENT', 'Urgent Alert (Red)')], default='INFO', max_length=20)),
                ('school', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
