"""
Django settings for sist_project project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Render-compatible filesystem fallback for SQLite persistence

def _ensure_parent_directory(path):
    parent = os.path.dirname(path)
    if parent and parent not in {'', '/'}:
        try:
            os.makedirs(parent, exist_ok=True)
        except PermissionError:
            # Render build containers may not have write access to persistent disk mount paths like /data.
            pass
        except OSError as exc:
            if exc.errno in {1, 13, 30}:  # EPERM, EACCES or EROFS
                pass
            else:
                raise

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-ojq&=sbj3yq@oyg9(8hq4u9#c=8wbd^c^k63!)cebc@6wq5%_7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]
render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_hostname:
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_hostname}')
CSRF_TRUSTED_ORIGINS.append('https://kisii-university-digital-logbook.onrender.com')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core', # Your SIST logbook app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sist_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # FIXED: Tells Django to look at your templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Added for debug contexts
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sist_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASE_URL = os.environ.get('DATABASE_URL')
SQLITE_DB_PATH = os.environ.get('SQLITE_DB_PATH')
USE_SQLITE = os.environ.get('USE_SQLITE', 'false').lower() in {'1', 'true', 'yes', 'on'}
IS_RENDER = os.environ.get('RENDER', '').lower() in {'1', 'true', 'yes', 'on'}
LEGACY_RENDER_DATABASE_NAME = False
USING_POSTGRES = False

# A real PostgreSQL URL must win over stale SQLite variables left in an
# existing Render service. This makes the Neon migration safe to deploy.
if DATABASE_URL and '://' in DATABASE_URL:
    USE_SQLITE = False

if DATABASE_URL and not USE_SQLITE:
    if '://' not in DATABASE_URL:
        # Existing Render services can retain a legacy database-name value such
        # as "dhangongo". It is not a usable connection string, so it must not
        # prevent collectstatic or migrations from starting.
        if IS_RENDER:
            USE_SQLITE = True
            LEGACY_RENDER_DATABASE_NAME = True
        else:
            raise ImproperlyConfigured(
                'DATABASE_URL is invalid. It must be a full connection string like postgres://user:pass@host:port/dbname, not just a service name.'
            )

    if not USE_SQLITE:
        DATABASES = {
            'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=False)
        }
        USING_POSTGRES = True

if (SQLITE_DB_PATH or USE_SQLITE) and not USING_POSTGRES:
    # Prefer the explicitly-configured SQLITE_DB_PATH (used at runtime on Render).
    # If the configured parent directory can be created and is writable, use it.
    # In debug mode, fallback to BASE_DIR/db.sqlite3 if necessary. In production,
    # do not silently switch to an ephemeral local database.
    # A legacy DATABASE_URL must never override the configured persistent disk.
    candidate = SQLITE_DB_PATH or ('/data/db.sqlite3' if IS_RENDER else str(BASE_DIR / 'db.sqlite3'))
    parent = os.path.dirname(candidate)
    use_candidate = False
    if parent in ('', '/'):
        use_candidate = True
    else:
        _ensure_parent_directory(candidate)
        if os.path.isdir(parent) and os.access(parent, os.W_OK):
            use_candidate = True

    if use_candidate:
        sqlite_path = candidate
    elif IS_RENDER:
        # The persistent disk can be unavailable during the build container.
        # Keep its path rather than switching to the rebuilt app filesystem.
        sqlite_path = candidate
    elif DEBUG:
        sqlite_path = str(BASE_DIR / 'db.sqlite3')
    else:
        # During Render build containers the persistent mount at /data may
        # not be writable yet. Falling back to a local DB here prevents the
        # build step (collectstatic/migrate) from failing — the runtime
        # process will still prefer the persistent mount when available.
        import warnings
        warnings.warn(
            f"Falling back to local sqlite DB because '{candidate}' is not writable. "
            "Ensure the persistent mount is configured on the host for production.",
            RuntimeWarning,
        )
        sqlite_path = str(BASE_DIR / 'db.sqlite3')

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_path,
        }
    }
elif not USING_POSTGRES:
    if DEBUG:
        sqlite_path = str(BASE_DIR / 'db.sqlite3')
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': sqlite_path,
            }
        }
    else:
        raise ImproperlyConfigured('DATABASE_URL is not set. Production must use the Render database.')


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi' # FIXED: Set to local Kenyan Time for Kisii University logs

USE_I18N = True

USE_TZ = True


# ==============================================================================
# AUTHENTICATION & SECURITY CONTROLS
# ==============================================================================
# CRITICAL: Points Django to use our custom multi-role User model instead of the default one
AUTH_USER_MODEL = 'core.User'
AUTHENTICATION_BACKENDS = ['core.backends.RegistrationNumberAuthBackend']

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Use an absolute URL path so static paths resolve correctly from any page
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static', # FIXED: Tells Django where your custom CSS folder lives
]
# Directory to collect static files for production (used by collectstatic)
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media Uploads (For students uploading their 14-week attachment summary reports)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
import os

# Base directory path definitions

import os

# Base directory path definitions
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in {'true', '1', 'yes'}
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'odiwuorosano09@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Attachment Office <odiwuorosano09@gmail.com>')
# Public address used in email messages (never send local development URLs).
PUBLIC_SITE_URL = os.environ.get('PUBLIC_SITE_URL', 'https://kisii-university-digital-logbook.onrender.com')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
